# Generated by Django 6.0.5 on 2026-05-26 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_rapport', models.CharField(choices=[('performance', 'Rapport de performance'), ('sla', 'Rapport SLA'), ('activite', 'Rapport d activité'), ('agents', 'Rapport agents'), ('satisfaction', 'Rapport satisfaction clients')], max_length=20)),
                ('format_fichier', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel')], max_length=10)),
                ('periodicite', models.CharField(choices=[('hebdomadaire', 'Hebdomadaire'), ('mensuelle', 'Mensuelle'), ('personnalise', 'Personnalisé')], default='mensuelle', max_length=20)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('fichier', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('statut', models.CharField(choices=[('en_cours', 'Génération en cours'), ('termine', 'Terminé'), ('erreur', 'Erreur de génération')], default='en_cours', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('termine_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
