# Generated by Django 6.0.5 on 2026-05-26 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_notification', models.CharField(choices=[('ticket_cree', 'Ticket créé'), ('ticket_affecte', 'Ticket affecté à un agent'), ('ticket_statut_change', 'Statut ticket modifié'), ('ticket_resolu', 'Ticket résolu'), ('message_recu', 'Nouveau message reçu'), ('ticket_assigne', 'Nouveau ticket assigné'), ('sla_alerte', 'Alerte SLA — approche dépassement'), ('sla_depasse', 'SLA dépassé'), ('priorite_modifiee', 'Priorité ticket modifiée'), ('escalade_recue', 'Ticket escaladé reçu'), ('sla_depasse_superviseur', 'SLA dépassé — intervention requise'), ('surcharge_agent', 'Alerte surcharge agent'), ('erreur_systeme', 'Erreur critique système'), ('echec_smtp', 'Échec intégration SMTP/IMAP'), ('anomalie_securite', 'Anomalie de sécurité détectée')], max_length=30)),
                ('titre', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('canal', models.CharField(choices=[('inapp', 'Notification in-app'), ('email', 'Email'), ('both', 'In-app + Email')], default='both', max_length=10)),
                ('lu', models.BooleanField(default=False)),
                ('lu_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
