# Generated by Django 6.0.5 on 2026-05-26 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Escalation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_escalade', models.CharField(choices=[('manuelle', 'Manuelle'), ('automatique_sla', 'Automatique — SLA dépassé'), ('automatique_critique', 'Automatique — Ticket critique non pris en charge'), ('automatique_rouvert', 'Automatique — Ticket rouvert plusieurs fois')], default='manuelle', max_length=30)),
                ('motif', models.TextField()),
                ('statut', models.CharField(choices=[('en_attente', 'En attente de traitement'), ('prise_en_charge', 'Prise en charge par superviseur'), ('resolue', 'Résolue')], default='en_attente', max_length=20)),
                ('commentaire_superviseur', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prise_en_charge_at', models.DateTimeField(blank=True, null=True)),
                ('resolue_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
