# Generated by Django 6.0.5 on 2026-05-26 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('ouvert', 'Ouvert'), ('affecte', 'Affecté'), ('en_cours', 'En cours'), ('en_attente', 'En attente'), ('resolu', 'Résolu'), ('rouvert', 'Rouvert'), ('ferme', 'Fermé'), ('escalade', 'Escaladé')], default='ouvert', max_length=20)),
                ('criticite', models.CharField(choices=[('critique', 'Critique'), ('haute', 'Haute'), ('moyenne', 'Moyenne'), ('basse', 'Basse')], default='moyenne', max_length=20)),
                ('canal', models.CharField(choices=[('web', 'Portail Web'), ('email', 'Email'), ('telephone', 'Téléphone')], default='web', max_length=20)),
                ('categorie', models.CharField(choices=[('reseau', 'Réseau / Connectivité'), ('facturation', 'Facturation'), ('acces', 'Accès / Authentification'), ('bug', 'Bug / Erreur système'), ('materiel', 'Matériel / Infrastructure'), ('autre', 'Autre')], default='autre', max_length=50)),
                ('ia_confidence', models.FloatField(blank=True, null=True)),
                ('sla_deadline', models.DateTimeField(blank=True, null=True)),
                ('sla_respecte', models.BooleanField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('affecte_at', models.DateTimeField(blank=True, null=True)),
                ('pris_en_charge_at', models.DateTimeField(blank=True, null=True)),
                ('resolu_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='tickets/attachments/')),
                ('evaluation_note', models.IntegerField(blank=True, null=True)),
                ('evaluation_commentaire', models.TextField(blank=True, null=True)),
                ('evaluation_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TicketHistorique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ancien_status', models.CharField(max_length=20)),
                ('nouveau_status', models.CharField(max_length=20)),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
