# Generated by Django 6.0.5 on 2026-05-26 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('type_message', models.CharField(choices=[('public', 'Public'), ('interne', 'Note interne')], default='public', max_length=10)),
                ('lu', models.BooleanField(default=False)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='messages/attachments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
